### ISSUE TITLE
Game crashes upon launch on Pop!_OS 22.04 LTS

### ISSUE THREAD

**Issue by RUvlad1** [semyon422/soundsphere#14]
![Screenshot from 2023-12-04 16-00-40](https://github.com/semyon422/soundsphere/assets/60317461/9e314501-5665-4f9a-bbaf-11a3d5762491)

**Comment by semyon422** [comment]
What script are you using to run it? Appimage should work well on most systems.

**Comment by RUvlad1** [comment]
> What script are you using to run it? Appimage should work well on most systems.

the game-linux one, i dont think i tried game-appimage though

**Comment by RUvlad1** [comment]
> the game-linux one, i dont think i tried game-appimage though

just tried game-appimage and it works perfectly, oops
should i close the issue?

**Comment by semyon422** [comment]
I'll close it, thanks for playing
