### ISSUE TITLE
First launch downloads empty files and overwrites them

### ISSUE THREAD

**Issue by RUvlad1** [semyon422/soundsphere#20]
![image](https://github.com/semyon422/soundsphere/assets/60317461/11133b4e-60bf-40b5-909e-dab7dee9ddd2)
![image](https://github.com/semyon422/soundsphere/assets/60317461/a4515e3a-2b71-4c03-9c48-9acb257360c0)

i'm not sure why this is happening, i've tried running it with and without a vpn, no difference

**Comment by RUvlad1** [comment]
update again: the download link in the readme works just fine, how come they are different?

**Comment by semyon422** [comment]
Sorry for that, there was not enough space on the server and update was not full. Should be fixed now.
