### ISSUE TITLE
Bugs when downloading beatmaps/songs

### ISSUE THREAD

**Issue by bert093** [semyon422/soundsphere#22]
When I want to download just one beatmap in the direct option (I waited for it to finish), there is an error like this:
and that usually never happens before.

![Screenshot 2024-07-18 092119](https://github.com/user-attachments/assets/f3119c76-ecc2-4201-af33-182d774223d5)
![Screenshot 2024-07-18 092554](https://github.com/user-attachments/assets/bd753426-cbdc-499b-a51d-027cc1187da2)

**Comment by semyon422** [comment]
The game will not crash now. In such case it will save downloaded osz in userdata/charts/download. I think there is a bug on beatmap server that sends corrupted osz sometimes.

**Comment by bert093** [comment]
nice, it works now.
