### ISSUE TITLE
How dose the game file work? (question for dev/owner.)                                                                                      |BUG FOR THE GAME||

### ISSUE THREAD

**Issue by flaredaren** [semyon422/soundsphere#6]
Ive downloaded it but it open my "CMD THINGY" And the file dosen't work that way, If you know a way to download along with the app opening correctly, please let me know in the comments. 

- flare daren 

Posted on: THURSDAY/ SEPTEMBER 2 / 2021.

**Comment by JustVldKsh** [comment]
1. i know, i'm not a dev, but did you used semyon422/soundsphere-updater?
2. .bat files are command line (cmd) executeables, so start-win32.bat and start-win64.bat both do open the cmd (which is pretty much intended behaviour for those files) and this is probably intended at least for debug purposes
3. this issue probably can be closed unless op clarifies what exactly they have problems with

**Comment by semyon422** [comment]
You should download https://github.com/semyon422/soundsphere-updater and use it to install git and download the game. Also you can join our discord server https://discord.gg/ubKMtTk to get more help with the game
